---
# tasks file for consul-config
- debug:
    var: ec2_tag_Name
- name: search and replace _ with -
  command: echo "{{ ec2_tag_Name }}" | sed -r 's/[_]+/-/g'
  register: ec2_tag_hostname
- name: register current hostname
  command: "/sbin/ifconfig|grep inet|head -1|sed 's/\:/ /'|awk '{print $3}'"
  register: hostname
- debug: var=hostname
- hostname:
    name: "{{ ec2_tag_hostname }}@{{ hostname }}"
